version: '3.8'
 
services:
  postgres:
    image: postgres:13
    container_name: authserviceIN6BV-postgres
    restart: always
    environment:
      POSTGRES_DB: KinalSportsIN6BV
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
 